# Generated by Django 4.2.7 on 2024-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartorderitem_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
